# Generated by Django 4.2.2 on 2023-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_estudiante',
            field=models.CharField(choices=[('becado', 'Estudiante Becado'), ('no-becado', 'Estudiante No Becado')], default='no-becado', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(verbose_name='edad de estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de estudiante'),
        ),
    ]
