# Generated by Django 4.2.2 on 2023-06-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_estudiante_tipo_estudiante_alter_estudiante_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de pais')),
                ('capital', models.CharField(max_length=30, verbose_name='Nombre de capital')),
            ],
        ),
    ]
